-- MySQL Script generated by MySQL Workbench
-- Mon Dec 21 15:39:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PPTS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PPTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PPTS` DEFAULT CHARACTER SET utf8 ;
USE `PPTS` ;

-- -----------------------------------------------------
-- Table `PPTS`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PPTS`.`Medicine` (
  `medicineID` INT NOT NULL,
  `medicineName` VARCHAR(45) NOT NULL,
  `medicineActiveSub` VARCHAR(45) NULL,
  `medicinePrice` DOUBLE NULL,
  `medicineStock` INT NULL,
  `medicineImageLocation` VARCHAR(200) NULL,
  PRIMARY KEY (`medicineID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PPTS`.`Other Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PPTS`.`Other Products` (
  `productID` INT NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  `productDescription` VARCHAR(120) NULL,
  `productPrice` DOUBLE NULL,
  `productStock` INT NULL,
  `productImageLocation` VARCHAR(200) NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PPTS`.`Receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PPTS`.`Receipts` (
  `receiptID` INT NOT NULL,
  `receiptDate` DATE NOT NULL,
  `receiptCustomerName` VARCHAR(45) NULL,
  `receiptNumberOfItems` INT NULL,
  `receiptTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`receiptID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
